### ISSUE TITLE
Multirun doesn't work in latest IJ 13 EA (130.1365)

### ISSUE THREAD

**Issue by jgindin** [rkhmelyuk/multirun#16]
Trying to invoke a Multirun configuration gives the following error:

com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/runners/ProgramRunner;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/execution/RunnerAndConfigurationSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/openapi/project/Project;)V: com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/runners/ProgramRunner;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/execution/RunnerAndConfigurationSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/openapi/project/Project;)V
java.lang.NoSuchMethodError: com.intellij.execution.runners.ExecutionEnvironment.<init>(Lcom/intellij/execution/runners/ProgramRunner;Lcom/intellij/execution/ExecutionTarget;Lcom/intellij/execution/RunnerAndConfigurationSettings;Lcom/intellij/execution/ui/RunContentDescriptor;Lcom/intellij/openapi/project/Project;)V
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:91)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:210)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:210)
    at com.khmelyuk.multirun.MultirunRunnerState.runConfigurations(MultirunRunnerState.java:210)
    at com.khmelyuk.multirun.MultirunRunnerState.execute(MultirunRunnerState.java:63)
    at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:37)
    at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:84)
    at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:202)
    at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:174)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:240)
    at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:253)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:77)
    at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:61)
    at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:101)
    at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:380)
    at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:58)
    at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:345)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:297)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:347)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:679)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:507)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:332)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by rkhmelyuk** [comment]
ExecutionEnvironment has very different c-tors in IDEA 12 and 13. Current version of ExecutionEnvironment https://github.com/JetBrains/intellij-community/blob/689f2a1686fd64ec84e5db955ac388a9436e71a0/platform/lang-api/src/com/intellij/execution/runners/ExecutionEnvironment.java

**Comment by rkhmelyuk** [comment]
Fixed by @jgindin and released in v0.8
https://github.com/rkhmelyuk/multirun/commit/863937ac7c5e807f62e7656d860c6e5831966a79

Thanks
